ARG AWS_REGION=us-east-1
FROM 763104351884.dkr.ecr.${AWS_REGION}.amazonaws.com/pytorch-inference:2.0.0-gpu-py310-cu118-ubuntu20.04-sagemaker
WORKDIR /workdir
COPY requirements.txt /workdir
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
RUN pip install -r requirements.txt
COPY tensorrt/*trt /opt/ml/model/
COPY src/ /opt/ml/model/code
EXPOSE 8080
ENTRYPOINT [ "python", "/usr/local/bin/dockerd-entrypoint.py" ]
